### PR TITLE
Enable GitHub password caching

### PR DESCRIPTION
**Pull request by srt32**
This update came out of
https://github.com/globality-corp/ansible-deploy/pull/4#issuecomment-131207343.

References:
- https://help.github.com/articles/caching-your-github-password-in-git/
- https://help.github.com/articles/which-remote-url-should-i-use/
- With 2FA: https://help.github.com/articles/creating-an-access-token-for-command-line-use/

### CODE REVIEW

**Comment by adamhadani** [comment]
LGTM we will find out soon enough if works when YL tries setting up!

**Comment by srt32** [comment]
Yup! I ran it locally and things seemed to be okay...

**Comment by yuhunglin** [comment]
@srt32 what is this huh? what did i get signed up to do :suspect:. Btw didn't get a chance to run through this since i tend to default to use ssh tokens for git.

**Comment by srt32** [comment]
@yuhunglin see https://github.com/globality-corp/ansible-deploy/pull/4#issuecomment-131207343 ;)

**Pull request merged**
